"""Markdown report + remediation brief formatting. Pure functions."""
from __future__ import annotations

from datetime import datetime, timezone

from .analyzer import ProjectReport, Finding


_SEVERITY_ICON = {
    "critical": "🛑",
    "high": "🔴",
    "medium": "🟠",
    "low": "🟡",
}


def _icon(sev: str) -> str:
    return _SEVERITY_ICON.get(sev, "•")


def format_report(report: ProjectReport, *, generated_at: datetime | None = None) -> str:
    ts = (generated_at or datetime.now(timezone.utc)).strftime("%Y-%m-%d %H:%M:%SZ")
    a = report.action_stats
    p = report.perf_stats
    lines: list[str] = []
    lines.append(f"# Project Telemetry Report — {report.project}")
    lines.append("")
    lines.append(f"_Generated: {ts}_")
    lines.append("")
    lines.append(f"- **Repo:** `{report.repo_path}`")
    lines.append(f"- **Team lead:** {report.team_lead}")
    lines.append(f"- **Findings:** {len(report.findings)}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("### User actions")
    lines.append("")
    lines.append(f"- Total: **{a.total}** (baseline ~{report.baseline_actions})")
    lines.append(f"- Errors: **{a.errors}** ({a.error_rate:.1%})")
    if a.top_errors:
        lines.append("- Top errors:")
        for key, count in a.top_errors:
            lines.append(f"  - `{key}` × {count}")
    lines.append("")
    lines.append("### Performance")
    lines.append("")
    baseline_p95 = f"{report.baseline_p95_ms:.0f}ms" if report.baseline_p95_ms else "n/a"
    lines.append(f"- Samples: **{p.samples}**")
    lines.append(f"- p50 / p95 / p99: **{p.p50_ms:.0f}ms / {p.p95_ms:.0f}ms / {p.p99_ms:.0f}ms**")
    lines.append(f"- Baseline p95: {baseline_p95}")
    if p.slowest_ops:
        lines.append("- Slowest ops (p95):")
        for op, v in p.slowest_ops:
            lines.append(f"  - `{op}` — {v:.0f}ms")
    lines.append("")
    lines.append("## Findings")
    lines.append("")
    if not report.findings:
        lines.append("_No anomalies detected in this window._")
    else:
        for i, f in enumerate(report.findings, 1):
            lines.append(f"### {i}. {_icon(f.severity)} [{f.severity.upper()}] {f.title}")
            lines.append("")
            lines.append(f"- **Kind:** `{f.kind}`")
            lines.append(f"- **Detail:** {f.detail}")
            lines.append(f"- **Suggested fix:** {f.suggested_fix}")
            lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("_Generated by `agents/project-analyzer/run.py`._")
    lines.append("")
    return "\n".join(lines)


def format_remediation_brief(report: ProjectReport, *, generated_at: datetime | None = None) -> str:
    """Concise hand-off brief for the target repo's team-lead.

    Returns empty string if there are no findings.
    """
    if not report.findings:
        return ""
    ts = (generated_at or datetime.now(timezone.utc)).strftime("%Y-%m-%d %H:%M:%SZ")
    top = _worst_finding(report.findings)
    lines: list[str] = []
    lines.append(f"# Remediation Brief — {report.project}")
    lines.append("")
    lines.append(f"_Generated: {ts}_")
    lines.append("")
    lines.append(f"- **Target repo:** `{report.repo_path}`")
    lines.append(f"- **Owner:** {report.team_lead}")
    lines.append(f"- **Top severity:** {top.severity.upper()} ({top.kind})")
    lines.append("")
    lines.append("## Action items")
    lines.append("")
    for i, f in enumerate(report.findings, 1):
        lines.append(f"{i}. **[{f.severity.upper()}] {f.title}**")
        lines.append(f"   - {f.detail}")
        lines.append(f"   - Fix: {f.suggested_fix}")
    lines.append("")
    return "\n".join(lines)


def _worst_finding(findings) -> Finding:
    order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    return sorted(findings, key=lambda f: order.get(f.severity, 99))[0]
